### PR TITLE
Set background color for ErrorPage

### PR DESCRIPTION
**Pull request by andyedinborough**
When using various browser developer tools with a dark theme, the text for the page is unreadable, because the background color has not been set, while the foreground color has.

### CODE REVIEW

**Comment by andyedinborough** [comment]
For example: 
image

**Comment by pranavkm** [comment]
You have to regenerate the designer files for this to take effect. The css files get inlined in to the designer file as part of being generated.

**Comment by pranavkm** [comment]
cc @kichalla - could you add instructions on running RazorPageGenerator?

**Comment by kichalla** [comment]
When you are under the project folder, you can use the `RazorPageGenerator` tool like below:

```
Usage:   dotnet razorpagegenerator <root-namespace-of-views>
Example: dotnet razorpagegenerator Microsoft.AspNetCore.Diagnostics.RazorViews
```

**Comment by andyedinborough** [comment]
Done.  Let me know if I did that right ;]

**Comment by pranavkm** [comment]
Might be the result of using a newer version of Razor but the designer formats some of the other generated artifacts ever so slightly:

image

Would you mind running `samples/DeveloperExceptionPageSample` and pasting in the generated error page into jsfiddle or liveweave and paste it in here? Just want to make sure the page's rendering correctly.

**Comment by andyedinborough** [comment]
Done:  https://jsfiddle.net/andyedinborough/fe15nty2/
image

**Comment by pranavkm** [comment]
This looks pretty great. I was talking to @sebastienros offline and he recommended doing more and using a css reset script (something like http://html5doctor.com/html-5-reset-stylesheet) so similar themeing issues don't affect the diagnostics page. I'm not super sure we need all of that. Let me run it by @Eilon for his thoughts on this.

**Comment by Eilon** [comment]
Eh, I don't think we need the full reset script because this is only needed for a more obscure dev scenario. I'm fine just setting the white background, though.

Don't we need to update this in all our error pages, though? @kichalla ?

**Comment by andyedinborough** [comment]
If you'd like to see it with a reset, I created https://github.com/andyedinborough/Diagnostics/tree/add-normalize, https://jsfiddle.net/andyedinborough/3y3defht/.

image

**Comment by sebastienros** [comment]
If you decide to set the background, then you have to also set the foreground color. Then by extension you should set the size, the line-height, the weight, and probably the font (with fall-backs). For each of the styles the page uses: headers, code, ...

**Comment by Eilon** [comment]
@sebastienros I don't entirely agree with that, though I agree with your statement in general. The only supported scenario for this page is to have it "full screen" in a browser window. Browsers don't need reset scripts. It just so happens that in some obscure (i.e. not-really-supported scenarios) there is a need to reset some styles.

**Comment by andyedinborough** [comment]
The foreground has been set, and that's the problem.  The font-size and weight have been set also.

**Comment by sebastienros** [comment]
> in some obscure (i.e. not-really-supported scenarios) there is a need to reset some styles

I agree, and when resetting "some styles" you need to reset the related ones. For instance background goes in pair with foreground. And this was the actual issue, the foreground was set and not the background. So I agree with the solution as the two of then are set.

I would still suggest to set the other elements I mentioned, to have a deterministic render.

> Browsers don't need reset scripts

We'll talk about this one offline ;)

**Comment by pranavkm** [comment]
Merging in as is. Thanks for the PR!

**Pull request merged**
