### PR TITLE
Remove hosting dependency on diagnostics package

### PR DESCRIPTION
**Pull request by Praburaj**
Fixes: #118 

@davidfowl

### CODE REVIEW

**Comment by Praburaj** [comment]
@muratg

**Comment by muratg** [comment]
Looks like Travis and AppVeyor are failing, any idea why?  Other than that, change looks good.

:shipit:

**Comment by Praburaj** [comment]
Thanks @muratg I think I sent the PR when there was a change in EF that was not propagated by a successful Coherence-Signed build. So the build on travis ci was failing since it builds against the vnext myget feed. I hope this should succeed if Coherence-Signed has passed. But I'll double check before pushing the change.

**Comment by Praburaj** [comment]
Looks like some tests are failing due to a known DI issue now. This should be independent of this change.

**Pull request merged**
