### PR TITLE
Fixing tests to work in Mono

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by kichalla** [comment]
:shipit:

**Comment by BrennanConroy** [comment]
Still fails on Travis

**Comment by kichalla** [comment]
I believe this is because earlier these tests were not enabled for CoreClr but looks like @pranavkm's recent change added it in project.json

**Comment by pranavkm** [comment]
Yup. I was trying to use Travis to test the PR. Trying it out locally now.

**Comment by pranavkm** [comment]
Updated and enabled tests to run on CoreCLR.

**Pull request closed without merging**
