### PR TITLE
[Fixes #288] DeveloperExceptionPage needs better text spacing on OSX/Safari

### LINKED ISSUE #288: DeveloperExceptionPage needs better text spacing on OSX/Safari
image

### PR DESCRIPTION
**Pull request by kichalla**
**Compile time error:**
**Before**
compiletimeerror-before

**After**
compiletimeerror-after

**Runtime error**
**Before**
runtimeerror-before

**After**
runtimeerror-after

@Eilon @rynowak This issue repros on all browsers actually. We didn't catch it probably because we probably didn't test with exceptions which is resulting in multi-line error message(which is what view compilation error is generating)

### CODE REVIEW

**Comment by pranavkm** [comment]
Could we review at all the styling \ formatting issues with the Diagnostics page in general rather than changing them piecemeal like this? https://github.com/aspnet/Diagnostics/issues/319 is another issue that would be useful to address.

**Comment by Eilon** [comment]
@pranavkm we could, but this issue is the most pressing one, so it'd be good to just get that fix out. The other bug is a bit more work.

**Comment by Eilon** [comment]
:shipit:

**Comment by kichalla** [comment]
e3e092ec6030b0d8e336ec63c8040ac46ba29009

**Pull request closed without merging**
