### PR TITLE
* Remove ICompilation* interfaces from Diagnostics

### LINKED ISSUE #111: Delete the Compilation interfaces
/cc @pranavkm

### PR DESCRIPTION
**Pull request by pranavkm**
* Removing error message from CompilationErrorPage since it repeats
 individual errors.

 Fixes #111

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
Screenshot?

**Comment by pranavkm** [comment]
capture

**Comment by Tratcher** [comment]
:shipit:

**Pull request closed without merging**
