### PR TITLE
Fixing runtime info middleware on coreclr

### PR DESCRIPTION
**Pull request by Praburaj**
Also adding more information like OS, runtime type and architecture to the info page.

@victorhurdugaci

### CODE REVIEW

**Comment by Praburaj** [comment]
This is the updated runtime info page: 

image

**Comment by victorhurdugaci** [comment]
Can we please make the fields one liners? So instead of 8 lines you only have 4

**Comment by Praburaj** [comment]
@victorhurdugaci updated PR. Here is the new screenshot.
image

**Comment by victorhurdugaci** [comment]
:shipit:

**Pull request merged**
