### PR TITLE
Allow collapse and expand of source code

### LINKED ISSUE #264: Source code no longer expands/collapses
Clicking error no longer expands.

Html still has extra lines in the html, looks like javascript is busted

errorpage

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Fixes #264.

Note that CompilationErrorPage.cs and ErrorPage.cs are generated, no need to review them.

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
CC @davidfowl & @loudej 
@loudej I basically did exactly what you said in the bug.

**Comment by lodejard** [comment]
:shipit:

Can I still say that? :D

**Comment by davidfowl** [comment]
👍

**Comment by davidfowl** [comment]
:shipit:

**Pull request merged**
