### PR TITLE
Removed SetDefaultVisibility for ErrorPageOptions

### PR DESCRIPTION
**Pull request by henkmollema**
- Removed `SetDefaultVisibility` method from `(Database)ErrorPageOptions`
- `(Database)ErrorPageOptions` properties are now auto-properties since there is no default visibility anymore
- Removed `isDevMode` parameter from `ErrorPageMiddleware` ctor
- Removed comments from `ErroPageExtensions.UseErrorPage()`
- Updated Entity tests

#130

### CODE REVIEW

**Comment by Tratcher** [comment]
Looks good.

**Comment by Tratcher** [comment]
Merged

**Comment by davidfowl** [comment]
We should remove ErrorPageOptions all together

**Comment by henkmollema** [comment]
@davidfowl how will that look like? Just show everything by default?

**Comment by davidfowl** [comment]
Yes, thats why the project template has a switch.

**Pull request closed without merging**
