### PR TITLE
Use default encoders all the time

### LINKED ISSUE #234: Diagnostics should register encoders in startup or use default values all the time
See here - https://github.com/aspnet/Diagnostics/blob/dev/src/Microsoft.AspNet.Diagnostics/Views/BaseView.cs#L69 where the body of the extension method is:

```C#
public static HtmlEncoder GetHtmlEncoder(this IServiceProvider serviceProvider)
{
    return (HtmlEncoder)serviceProvider?.GetService(typeof(HtmlEncoder)) ?? HtmlEncoder.Default;
}
```

We should either require registering encoders in the service container or use `*Encoder.Default` all the time. I'd prefer the latter since these are diagnostic pages and are not meant for production views.

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #234

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @Eilon \ @ryanbrandenburg

**Comment by Eilon** [comment]
:shipit: and I'm amazed there was a specific test for this...

**Comment by ryanbrandenburg** [comment]
Seems alright. was the existing test you removed mocking to much to be useful or something?

**Comment by davidfowl** [comment]
Yes! Can we also remove `Get*Encoder`

**Comment by pranavkm** [comment]
Yeah, that was the plan @davidfowl

**Comment by pranavkm** [comment]
@ryanbrandenburg it was verifying the scenario we removed. We just use the default encoders and not the one specified in the service container.

**Pull request merged**
