### PR TITLE
Show full generated output option for Razor compilation errors

### LINKED ISSUE #303: Show full generated output option for razor compilation errors
Right now, if you get a Razor compilation error, the developer error page shows just the offending fragment of generated C#. In Web Forms and Razor previously, there was a link on the error page to toggle showing the full generated output. This was a great tool for learning how Razor was turned in to C# before being compiled.

Can we please add this option back.

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #303

### CODE REVIEW

**Comment by pranavkm** [comment]
http://plnkr.co/edit/7bLEnrKH36aee1YK7jZm?p=preview is what this looks like. cc @davidfowl \ @Eilon

**Comment by Eilon** [comment]
Very nice. I triaged and assigned https://github.com/aspnet/Diagnostics/issues/303 to you as well 😄 *ahem*

cc @DamianEdwards as well. I assume you'd love to have this in 1.1.0-RTM?

**Comment by DamianEdwards** [comment]
Yes please!

**Comment by Eilon** [comment]
Cool. @pranavkm can we add some kind of test for this?

**Comment by pranavkm** [comment]
I'll add tests to Mvc as a follow up to this PR.

**Pull request merged**
