### PR TITLE
Fixing runtime info middleware on coreclr

### PR DESCRIPTION
**Pull request by Praburaj**
Fixes: https://github.com/aspnet/Diagnostics/issues/108

@victorhurdugaci @davidfowl

### CODE REVIEW

**Comment by davidfowl** [comment]
I would wait on @victorhurdugaci's change to add IRuntimeEnvironment

**Comment by Praburaj** [comment]
I see. Is there a tracking bug on `IRuntimeEnvironment`. I can link this bug to that and close this PR.

**Comment by victorhurdugaci** [comment]
no, keep this PR open and use IRuntimeEnvironment once this https://github.com/aspnet/dnx/pull/1650 is in

**Comment by Praburaj** [comment]
@victorhurdugaci Looks like you've got a ship it on the other PR. I'll update this PR once you merge that.

**Pull request merged**
