### PR TITLE
Add EFCore DbContext check

### PR DESCRIPTION
**Pull request by rynowak**
First draft of a DbContext-based EFCore health check - the sample is probably the best place to start.

### CODE REVIEW

**Comment by rynowak** [comment]
> but looking at this I wonder if you really need to use IOptionsMonitor.

I thought IOptionsMonitor was the way to do named options? 🤷‍♂️

**Comment by divega** [comment]
> > but looking at this I wonder if you really need to use IOptionsMonitor.
> 
> I thought IOptionsMonitor was the way to do named options? 🤷‍♂️

Maybe. As I said, I don’t remember enough. @haok?

**Comment by HaoK** [comment]
Yeah no other way to do named options other than `IOptionsMonitor`, looks fine to me

**Comment by rynowak** [comment]
Cool, thanks friends!

**Comment by rynowak** [comment]
Will need to wait to add packages to aspnet/Universe before merging 😲

**Pull request merged**
